/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import java.util.ArrayList;

/**
 *
 * @author ivo.dipumpo
 */
public class FileTransfer extends javax.swing.JPanel {

    /**
     * Creates new form FileTransfer
     */
    public FileTransfer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jComboBoxUserSelect = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButtonSendRequest = new javax.swing.JButton();
        jLabelFile = new javax.swing.JLabel();
        jButtonScegliFile = new javax.swing.JButton();

        jComboBoxUserSelect.setModel(new ComboModel(new ArrayList()));
        jComboBoxUserSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUserSelectActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jButtonSendRequest.setText("jButton1");

        jLabelFile.setText("jLabel2");

        jButtonScegliFile.setText("jButton1");
        jButtonScegliFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonScegliFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSendRequest)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelFile, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxUserSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jButtonScegliFile))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxUserSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFile, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonScegliFile))
                .addGap(18, 18, 18)
                .addComponent(jButtonSendRequest)
                .addContainerGap(144, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonScegliFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonScegliFileActionPerformed
        // TODO add your handling code here:
        jFileChooser1.setVisible(true);
    }//GEN-LAST:event_jButtonScegliFileActionPerformed

    private void jComboBoxUserSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUserSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUserSelectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonScegliFile;
    public javax.swing.JButton jButtonSendRequest;
    public javax.swing.JComboBox jComboBoxUserSelect;
    public javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabelFile;
    // End of variables declaration//GEN-END:variables
}
