/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import org.jivesoftware.smack.ConnectionListener;
import org.jivesoftware.smack.XMPPConnection;

/**
 *
 * @author ivo.dipumpo
 */
public class JPanelConnectionStatus extends javax.swing.JPanel implements ConnectionListener{

    /**
     * Creates new form JPanelConnectionStatus
     */
    public JPanelConnectionStatus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelStatus = new javax.swing.JLabel();
        jLabelColor = new javax.swing.JLabel();

        jLabelStatus.setForeground(new java.awt.Color(0, 153, 102));
        jLabelStatus.setText("jLabel1");

        jLabelColor.setBackground(new java.awt.Color(255, 0, 51));
        jLabelColor.setText("jLabel2");
        jLabelColor.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(jLabelStatus)
                .addGap(64, 64, 64)
                .addComponent(jLabelColor)
                .addGap(147, 147, 147))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStatus)
                    .addComponent(jLabelColor)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabelColor;
    private javax.swing.JLabel jLabelStatus;
    // End of variables declaration//GEN-END:variables

    @Override
    public void connected(XMPPConnection connection) {
        this.jLabelColor.setBackground(Color.green);
        this.jLabelStatus.setText(String.valueOf(connection.isConnected()));
    }

    @Override
    public void authenticated(XMPPConnection connection, boolean resumed) {
       
    }

    @Override
    public void connectionClosed() {
         this.jLabelColor.setBackground(Color.red);
    }

    @Override
    public void connectionClosedOnError(Exception e) {
        this.jLabelColor.setBackground(Color.red);
    }

    @Override
    public void reconnectionSuccessful() {
      this.jLabelColor.setBackground(Color.green);
    }

    @Override
    public void reconnectingIn(int seconds) {
         this.jLabelColor.setBackground(Color.red);
    }

    @Override
    public void reconnectionFailed(Exception e) {
        this.jLabelColor.setBackground(Color.red);
    }
}
