/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import org.jivesoftware.smack.ConnectionListener;
import org.jivesoftware.smack.XMPPConnection;

/**
 *
 * @author ivo.dipumpo
 */
public class JPanelConnectionStatus extends javax.swing.JPanel {

    /**
     * Creates new form JPanelConnectionStatus
     */
    public JPanelConnectionStatus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelStatus = new javax.swing.JLabel();
        jLabelColor = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 0, 204), null));
        setToolTipText("");

        jLabelStatus.setForeground(new java.awt.Color(0, 153, 102));
        jLabelStatus.setText("jLabel1");

        jLabelColor.setBackground(new java.awt.Color(255, 0, 51));
        jLabelColor.setForeground(new java.awt.Color(255, 0, 51));
        jLabelColor.setText("non connesso");
        jLabelColor.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(jLabelStatus)
                .addGap(64, 64, 64)
                .addComponent(jLabelColor)
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelColor)
                    .addComponent(jLabelStatus))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("pp");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabelColor;
    public javax.swing.JLabel jLabelStatus;
    // End of variables declaration//GEN-END:variables

   
}
